project:
  type: website
  output-dir: docs

website:
  search: false
  site-url: https://ldliao.github.io/
  title: "Lauren Liao"
  navbar:
    right:
      - href: index.qmd
        text: Home
      # - href: projects.qmd
      #   text: Projects
      - href: https://ldliao.shinyapps.io/jointVIP/
        text: Projects
      - href: cv/liao_cv_2023.pdf
        text: CV
  page-footer:
    left: 
      - text: "Copyright Lauren Liao 2023"
    right:
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=PaxXaf8AAAAJ&hl=en&oi=ao
      - icon: github
        href: https://github.com/ldliao
      - icon: twitter
        href: https://twitter.com/ldliao
      - icon: linkedin
        href: https://www.linkedin.com/in/ldliao/
      - icon: envelope-fill
        href: mailto:ldliao@berkeley.edu

format:
  html:
    mainfont: Avenir
    theme: 
      - custom.scss
    css: styles.css
    toc: true
    # page-layout: full
    fontsize: 10;

editor: visual

